-- Create students table
CREATE TABLE public.students (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  register_number TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  semester INTEGER NOT NULL,
  batch TEXT NOT NULL,
  degree TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create courses table with predefined courses
CREATE TABLE public.courses (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create grades table
CREATE TABLE public.grades (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  course_id UUID NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  is_passed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE(student_id, course_id)
);

-- Enable Row Level Security
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (since this is for faculty use)
CREATE POLICY "Allow all operations on students" ON public.students FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on courses" ON public.courses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on grades" ON public.grades FOR ALL USING (true) WITH CHECK (true);

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  return NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_students_updated_at
  BEFORE UPDATE ON public.students
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_grades_updated_at
  BEFORE UPDATE ON public.grades
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Insert predefined courses
INSERT INTO public.courses (code, name) VALUES
('21ASO301T', 'ELEMENTS OF AERONAUTICS'),
('21AUO101T', 'HYBRID AND ELECTRIC VEHICLES'),
('21BMO121T', 'FUNDAMENTALS OF BIOMEDICAL ENGINEERING'),
('21BTB102T', 'INTRODUCTION TO COMPUTATIONAL BIOLOGY'),
('21BTO101T', 'HUMAN HEALTH AND DISEASES'),
('21CEO307T', 'MUNICIPAL SOLID WASTE MANAGEMENT'),
('21CEO308T', 'DISASTER MITIGATION AND MANAGEMENT'),
('21CEO309T', 'WATER POLLUTION AND ITS MANAGEMENT'),
('21CEO310T', 'GLOBAL WARMING AND CLIMATE CHANGE'),
('21CSC101T', 'OBJECT ORIENTED DESIGN AND PROGRAMMING'),
('21CSC201J', 'DATA STRUCTURES AND ALGORITHMS'),
('21CSC202J', 'OPERATING SYSTEMS'),
('21CSC203P', 'ADVANCED PROGRAMMING PRACTICE'),
('21CSC204J', 'DESIGN AND ANALYSIS OF ALGORITHMS'),
('21CSC205P', 'DATABASE MANAGEMENT SYSTEMS'),
('21CSC206T', 'ARTIFICIAL INTELLIGENCE'),
('21CSC301T', 'FORMAL LANGUAGE AND AUTOMATA'),
('21CSC302J', 'COMPUTER NETWORKS'),
('21CSC305P', 'MACHINE LEARNING'),
('21CSE251T', 'DIGITAL IMAGE PROCESSING'),
('21CSE253T', 'INTERNET OF THINGS'),
('21CSE254T', 'BIO INSPIRED COMPUTING'),
('21CSE255T', 'COMPUTER GRAPHICS AND ANIMATION'),
('21CSE292P', 'ARTIFICIAL INTELLIGENCE OF THINGS'),
('21CSE296P', 'IOS APP PROTOTYPE DESIGN AND DEVELOPMENT'),
('21CSE297P', 'IOS APP DEVELOPMENT SKILLS'),
('21CSE303P', 'INTRODUCTION TO PRODUCT DESIGN AND INNOVATION'),
('21CSE306J', 'QUANTUM COMPUTATION'),
('21CSE306P', 'APPLIED GENERATIVE AI'),
('21CSE307J', 'QUANTUM MACHINE LEARNING'),
('21CSE308J', 'OFFENSIVE SECURITY'),
('21CSE311J', 'CLOUD BASED REMOTE SENSING AND GIS'),
('21CSE324P', 'NP COMPLETENESS AND BEYOND'),
('21CSE325P', 'QUANTUM COMMUNICATION AND CRYPTOGRAPHY'),
('21CSE351T', 'COMPUTATIONAL LOGIC'),
('21CSE354T', 'FULL STACK WEB DEVELOPMENT'),
('21CSE359T', 'INFORMATION STORAGE AND MANAGEMENT'),
('21CSE361T', 'DATABASE SECURITY AND PRIVACY'),
('21CSE388T', 'INFORMATION VISUALIZATION'),
('21CSE390T', 'VIRTUALIZATION AND HYPER CONVERGED INFRASTRUCTURE'),
('21CSE395P', 'PRINCIPLES OF UX / UI DESIGN'),
('21CSE399J', 'COMPREHENSIVE LINUX FOR ALL'),
('21CSO361P', 'IDEA GENERATION APP DESIGN'),
('21CSS101J', 'PROGRAMMING FOR PROBLEM SOLVING'),
('21CSS201T', 'COMPUTER ORGANIZATION AND ARCHITECTURE'),
('21CYB101J', 'CHEMISTRY'),
('21CYM101T', 'ENVIRONMENTAL SCIENCE'),
('21DCO101P', 'ENTREPRENEURSHIP BOOTCAMP'),
('21DCS201P', 'DESIGN THINKING AND METHODOLOGY'),
('21ECO101T', 'SHORT RANGE WIRELESS COMMUNICATION'),
('21ECO102J', 'ELECTRONIC CIRCUITS AND SYSTEMS'),
('21ECO103T', 'MODERN WIRELESS COMMUNICATION SYSTEMS'),
('21ECO104J', 'PCB DESIGN AND MANUFACTURING'),
('21ECO105T', 'FIBER OPTICS AND OPTOELECTRONICS'),
('21ECO106J', 'EMBEDDED SYSTEM DESIGN USING ARDUINO'),
('21ECO107J', 'EMBEDDED SYSTEM DESIGN USING RASPBERRY PI'),
('21EEO301T', 'E-MOBILITY'),
('21EEO303T', 'E-WASTE MANAGEMENT'),
('21EEO305T', 'SURVEILLANCE TECHNOLOGY'),
('21EEO307T', 'CLEAN AND GREEN ENERGY'),
('21EES101T', 'ELECTRICAL AND ELECTRONICS ENGINEERING'),
('21GEO101T', 'BEHAVIORAL BIOLOGY'),
('21GEO102T', 'MICROBES AND SOCIETY'),
('21GNH101J', 'PHILOSOPHY OF ENGINEERING'),
('21GNM101L', 'PHYSICAL AND MENTAL HEALTH USING YOGA'),
('21GNP301L', 'COMMUNITY CONNECT'),
('21IPE335J', 'FUNCTIONAL TESTING AND PROGRAMMING'),
('21IPE401J', 'CAPSTONE PROGRAM IN ELECTRONIC COOLING'),
('21IPE416T', 'SCRIPTING AND APPLICATION DEVELOPMENT FUNDAMENTALS'),
('21LEH101T', 'COMMUNICATIVE ENGLISH'),
('21LEH102T', 'CHINESE'),
('21LEH105T', 'JAPANESE'),
('21LEM101T', 'CONSTITUTION OF INDIA'),
('21LEM201T', 'PROFESSIONAL ETHICS'),
('21LEM202T', 'UNIVERSAL HUMAN VALUES - II: UNDERSTANDING HARMONY AND ETHICAL HUMAN CONDUCT'),
('21LEM301T', 'INDIAN ART FORM'),
('21MAB101T', 'CALCULUS AND LINEAR ALGEBRA'),
('21MAB102T', 'ADVANCED CALCULUS AND COMPLEX ANALYSIS'),
('21MAB201T', 'TRANSFORMS AND BOUNDARY VALUE PROBLEMS'),
('21MAB204T', 'PROBABILITY AND QUEUEING THEORY'),
('21MAB302T', 'DISCRETE MATHEMATICS'),
('21MEO101T', 'FUNDAMENTALS OF COMPOSITE MATERIALS'),
('21MEO102T', 'REVERSE ENGINEERING AND 3D PRINTING'),
('21MEO104T', 'TQM AND RELIABILITY ENGINEERING'),
('21MEO106T', 'INTRODUCTION TO ROBOTICS'),
('21MEO110T', 'ENERGY SYSTEMS FOR SUSTAINABLE BUILDINGS'),
('21MEO113J', 'ELECTRONICS THERMAL MANAGEMENT'),
('21MES101L', 'BASIC CIVIL AND MECHANICAL WORKSHOP'),
('21MES102L', 'ENGINEERING GRAPHICS AND DESIGN'),
('21MGO101T', 'EMOTIONAL INTELLIGENCE'),
('21MGO104T', 'STRESS MANAGEMENT'),
('21MGO107T', 'FLEXIBLE WORK MODELS AND EMPLOYEE WELL-BEING'),
('21NTO301T', 'APPLICATIONS OF NANOTECHNOLOGY'),
('21NTO304T', 'ENVIRONMENTAL NANOTECHNOLOGY'),
('21NTO307T', 'NANOCOMPUTING'),
('21NTO308T', 'SMART SENSOR SYSTEMS'),
('21PDH201T', 'SOCIAL ENGINEERING'),
('21PDM101L', 'PROFESSIONAL SKILLS AND PRACTICES'),
('21PDM102L', 'GENERAL APTITUDE'),
('21PDM201L', 'VERBAL REASONING'),
('21PDM202L', 'CRITICAL AND CREATIVE THINKING SKILLS'),
('21PYB102J', 'SEMICONDUCTOR PHYSICS AND COMPUTATIONAL METHODS'),
('CSV0660J', 'FULL-STACK WEB DEVELOPMENT');

-- Create indexes for better performance
CREATE INDEX idx_students_register_number ON public.students(register_number);
CREATE INDEX idx_students_batch ON public.students(batch);
CREATE INDEX idx_students_semester ON public.students(semester);
CREATE INDEX idx_grades_student_id ON public.grades(student_id);
CREATE INDEX idx_grades_course_id ON public.grades(course_id);
CREATE INDEX idx_grades_is_passed ON public.grades(is_passed);
CREATE INDEX idx_courses_code ON public.courses(code);